### ISSUE TITLE
Findings from fuzzing DPE

### ISSUE THREAD

**Issue by benjamindoron** [chipsalliance/caliptra-dpe#130]
After the "platform" refactor, fuzzing DPE with https://github.com/chipsalliance/caliptra-dpe/pull/129 - specifically, libFuzzer - panics with the following:
`thread '<unnamed>' panicked at 'source slice length (0) does not match destination slice length (2048)', <caliptra-sw>/runtime/dpe/platform/src/default.rs:158:13`

Specifically, the following (deserialised) input panics:
`GetCertificateChain(GetCertificateChainCmd { offset: 274, size: 0 })`

**Comment by sree-revoori1** [comment]
@jhand2 I think this should be fixed with https://github.com/chipsalliance/caliptra-dpe/pull/169. Thoughts?

**Comment by sree-revoori1** [comment]
Fixed with https://github.com/chipsalliance/caliptra-dpe/pull/169
