### ISSUE TITLE
Test Infrastructure-Split tests into multiple files 

### ISSUE THREAD

**Issue by pdharshinik** [chipsalliance/caliptra-dpe#137]
Split the tests based on test type for better manageability.

**Comment by steffy3494** [comment]
Split test approach:

Under https://github.com/chipsalliance/caliptra-dpe/blob/main/verification folder, there is only one test file called verification_test.go. 

In there, DPE commands are getting validated, and those commands are having a different method. Hence, we are splitting the test file based on DPE commands. 

We are separating commands and their helper functions as a separate file. Later when we introduce new commands we can add in the existing files or create new one based on functionality.

**Comment by jhand2** [comment]
> Common file in the same module which will have a path to simulator/emulator executable and an extension to the main DPE transport interface with test hooks (TestDPEInstance interface).

One notable difference between the simulator and the Caliptra emulator

The DPE simulator can accept flags for different DPE features being enabled/disabled. The Caliptra implementation will have a fixed set of enabled features (I think they will all be enabled). So that will need to be handled differently.

**Comment by steffy3494** [comment]
Raised the pull request for the addition of a switch between simulator and emulator.
https://github.com/chipsalliance/caliptra-dpe/pull/150

Added the dummy value for the emulator. Once it is implemented, will add the actual enabled feature.
