### ISSUE TITLE
Test Infrastructure - Implement a transport  to send DPE commands 

### ISSUE THREAD

**Issue by pdharshinik** [chipsalliance/caliptra-dpe#138]
Implement a transport to allow the DPE verification tests to send DPE commands to the Caliptra Emulator via the CModel bindings

Cgo bindings to be used

**Comment by hpya93** [comment]
Have tried the following:
- Build the caliptra-sw through the build command in Readme.
- Turns out that out/caliptra_model.h is getting created on "cargo build" through cbindgen, explored it.
- Trying to utilize Rust function from Go file.

**Comment by prems95** [comment]
Have tried the following,
Explored the build options in caliptra-sw.
Explored the methods for executing commands using caliptra_api.c
Working on invoking commands using go file.
