### ISSUE TITLE
In DefaultPlatform, the issuer name should match the alias key cert

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-dpe#172]
# Make issuer match cert chain

The DPE default platform has

1. One self-signed cert in the cert chain:

https://github.com/chipsalliance/caliptra-dpe/blob/a7e07664fc17b29f9ee0c588a6073ed12753d013/platform/src/default.rs#L18

2. An issuer name:

https://github.com/chipsalliance/caliptra-dpe/blob/a7e07664fc17b29f9ee0c588a6073ed12753d013/platform/src/default.rs#L61-L67

We should make the issuer name in 2 be the same as the subject name in 1. This will ensure that the issuer name in DPE leaf certs will match the issuing cert and cert chain validation will work.

# Make the alias cert match the algorithm of the platform being used

1. If profile is p256, cert chain key should be p256
2. If p384, cert chain should have p384 key

# Make crypto key and cert chain match

The OpensslCrypto implementation can take a key at build time to use as the alias key: https://github.com/chipsalliance/caliptra-dpe/blob/a7e07664fc17b29f9ee0c588a6073ed12753d013/crypto/build.rs#L20

We should make this key the same key that's in the cert in DefaultPlatform

**Comment by sree-revoori1** [comment]
Fixed by https://github.com/chipsalliance/caliptra-dpe/pull/173
