### ISSUE TITLE
Context Handles Not Rotated on Error

### ISSUE THREAD

**Issue by sree-revoori1** [chipsalliance/caliptra-dpe#195]
NCC report page 31

**Comment by sree-revoori1** [comment]
We decided to not do this since rotating a handle on an error would mean that the caller no longer has access to that handle, since if a DPE command fails, we do not return the handle. Since rotating the handle destructively mutates DPE's context array, the old handle is invalid, and the caller has no way to access the new context corresponding to the rotated handle.

Another reason is that rotating the handle on error could be confusing in other ways such as if the input handle itself invalid or if the DPE command failed due to an error in generating the new handle.

**Comment by jhand2** [comment]
To expand on why we do not rotate context handles on error:

1. This would lead to inconsistent behavior on error. Some errors (such as INVALID_HANDLE) have no handle to rotate.
2. This encourages clients to interpret response structures inconsistently. On error, some fields (such as `new_context_handle`) would need to be interpreted, but others will hold invalid data (signatures, public keys, etc).
3. As correctly pointed out by NCC, failed commands SHALL NOT mutate the internal state of DPE. This greatly limits attacks against DPE which attempt to corrupt the internal state. This rule includes all internal state.

We will work to update the spec to clarify this edge case.
