### ISSUE TITLE
Implement additional commands in DPE Go client

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-dpe#248]
In the [DPE Go client](https://github.com/chipsalliance/caliptra-dpe/blob/main/verification/client.go), implement

* DeriveChild
* Sign
* ExtendTCI

**Comment by sree-revoori1** [comment]
Done in https://github.com/chipsalliance/caliptra-dpe/pull/253, https://github.com/chipsalliance/caliptra-dpe/pull/251, and https://github.com/chipsalliance/caliptra-dpe/pull/250
