### ISSUE TITLE
Make error enums hold i32

### ISSUE THREAD

**Issue by sree-revoori1** [chipsalliance/caliptra-dpe#330]
Error enums such as CryptoError, PlatformError, etc., often hold onto a u32 in order to allow the platform implementation to convey more information about what went wrong specifically. In some platforms however, library calls could return negative numbers so casting them to u32 would make us lose information. We should make these error enums hold i32s instead.

**Comment by jhand2** [comment]
I don't think it really loses information. Both are 32 bit values and can be converted back and forth. Either way there may be a mismatch with a platform library. So I don't think using u32 is any worse or better.
