### ISSUE TITLE
Consider deriving Debug only in test config

### ISSUE THREAD

**Issue by chrisfenner** [chipsalliance/caliptra-dpe#60]
Since the DPE implementation doesn't really have anything useful to *do* with a `Debug` string, we could probably bulk-update the `derive` attributes and move `Debug` into `#[cfg_attr(test`

**Comment by korran** [comment]
Do you have proof that these unused strings are being included in the binary? From my experience the compiler won't include them if they aren't used. And we should be adding tests for size/bloat regressions regardless of what we do here....

**Comment by chrisfenner** [comment]
I don't have proof. I created this bug to lift out this comment from a recent PR: https://github.com/chipsalliance/caliptra-dpe/pull/58#discussion_r1157835823

**Comment by jhand2** [comment]
Agreed if you don't use them then they don't be included in the binary. Just don't want to make the traits available and encourage people to write firmware that uses them.

Agreed tests for fw bloat are necessary either way. This has more to do with setting expectations on what is supported to contributors.

**Comment by jhand2** [comment]
Going to close this. I don't think this is a problem, compiler is smart enough to not include these strings.
